package nl.rijksoverheid.dcbs.verifier.models

object IsoCountries {

    val allCountries = listOf(
        IsoCountryInfo("Afghanistan", "004", "AF", "AFG", "+93", "AFN", "AS"),
        IsoCountryInfo("Åland Islands", "248", "AX", "ALA", "+358", "FIM", "EU"),
        IsoCountryInfo("Albania", "008", "AL", "ALB", "+355", "ALL", "EU"),
        IsoCountryInfo("Algeria", "012", "DZ", "DZA", "+213", "DZD", "AF"),
        IsoCountryInfo("American Samoa", "016", "AS", "ASM", "+684", "USD", "OC"),
        IsoCountryInfo("Andorra", "020", "AD", "AND", "+376", "EUR", "EU"),
        IsoCountryInfo("Angola", "024", "AO", "AGO", "+244", "AOA", "AF"),
        IsoCountryInfo("Anguilla", "660", "AI", "AIA", "+264", "XCD", "NA"),
        IsoCountryInfo("Antarctica", "010", "AQ", "ATA", "+672", "AUD", "AN"),
        IsoCountryInfo("Antigua and Barbuda", "028", "AG", "ATG", "+268", "XCD", "NA"),
        IsoCountryInfo("Argentina", "032", "AR", "ARG", "+54", "ARS", "SA"),
        IsoCountryInfo("Armenia", "051", "AM", "ARM", "+374", "AMD", "AS"),
        IsoCountryInfo("Aruba", "533", "AW", "ABW", "+297", "AWG", "NA"),
        IsoCountryInfo("Australia", "036", "AU", "AUS", "+61", "AUD", "OC"),
        IsoCountryInfo("Austria", "040", "AT", "AUT", "+43", "EUR", "EU"),
        IsoCountryInfo("Azerbaijan", "031", "AZ", "AZE", "+994", "AZN", "AS"),
        IsoCountryInfo("Bahamas", "044", "BS", "BHS", "+242", "BSD", "NA"),
        IsoCountryInfo("Bahrain", "048", "BH", "BHR", "+973", "BHD", "AS"),
        IsoCountryInfo("Bangladesh", "050", "BD", "BGD", "+880", "BDT", "AS"),
        IsoCountryInfo("Barbados", "052", "BB", "BRB", "+246", "BBD", "NA"),
        IsoCountryInfo("Belarus", "112", "BY", "BLR", "+375", "BYR", "EU"),
        IsoCountryInfo("Belgium", "056", "BE", "BEL", "+32", "EUR", "EU"),
        IsoCountryInfo("Belize", "084", "BZ", "BLZ", "+501", "BZD", "NA"),
        IsoCountryInfo("Benin", "204", "BJ", "BEN", "+229", "XOF", "AF"),
        IsoCountryInfo("Bermuda", "060", "BM", "BMU", "+441", "BMD", "NA"),
        IsoCountryInfo("Bhutan", "064", "BT", "BTN", "+975", "BTN", "AS"),
        IsoCountryInfo("Bolivia, Plurinational State of", "068", "BO", "BOL", "+591", "BOB", "SA"),
        IsoCountryInfo("Bonaire, Sint Eustatius and Saba", "535", "BQ", "BES", "+599", "USD", ""),
        IsoCountryInfo("Bosnia and Herzegovina", "070", "BA", "BIH", "+387", "BAM", "EU"),
        IsoCountryInfo("Botswana", "072", "BW", "BWA", "+267", "BWP", "AF"),
        IsoCountryInfo("Bouvet Island", "074", "BV", "BVT", "+47", "NOK", "AN"),
        IsoCountryInfo("Brazil", "076", "BR", "BRA", "+55", "BRL", "SA"),
        IsoCountryInfo("British Indian Ocean Territory", "086", "IO", "IOT", "+246", "USD", "AS"),
        IsoCountryInfo("Brunei Darussalam", "096", "BN", "BRN", "+673", "BND", "AS"),
        IsoCountryInfo("Bulgaria", "100", "BG", "BGR", "+359", "BGN", "EU"),
        IsoCountryInfo("Burkina Faso", "854", "BF", "BFA", "+226", "XOF", "AF"),
        IsoCountryInfo("Burundi", "108", "BI", "BDI", "+257", "BIF", "AF"),
        IsoCountryInfo("Cambodia", "116", "KH", "KHM", "+855", "KHR", "AS"),
        IsoCountryInfo("Cameroon", "120", "CM", "CMR", "+237", "XAF", "AF"),
        IsoCountryInfo("Canada", "124", "CA", "CAN", "+1", "CAD", "NA"),
        IsoCountryInfo("Cabo Verde", "132", "CV", "CPV", "+238", "CVE", "AF"),
        IsoCountryInfo("Cayman Islands", "136", "KY", "CYM", "+345", "KYD", "NA"),
        IsoCountryInfo("Central African Republic", "140", "CF", "CAF", "+236", "XAF", "AF"),
        IsoCountryInfo("Chad", "148", "TD", "TCD", "+235", "XAF", "AF"),
        IsoCountryInfo("Chile", "152", "CL", "CHL", "+56", "CLP", "SA"),
        IsoCountryInfo("China", "156", "CN", "CHN", "+86", "CNY", "AS"),
        IsoCountryInfo("Christmas Island", "162", "CX", "CXR", "+61", "AUD", "AS"),
        IsoCountryInfo("Cocos (Keeling) Islands", "166", "CC", "CCK", "+891", "AUD", "AS"),
        IsoCountryInfo("Colombia", "170", "CO", "COL", "+57", "COP", "SA"),
        IsoCountryInfo("Comoros", "174", "KM", "COM", "+269", "KMF", "AF"),
        IsoCountryInfo("Congo", "178", "CG", "COG", "+242", "XAF", "AF"),
        IsoCountryInfo("Congo, the Democratic Republic of the", "180", "CD", "COD", "+243", "CDF", "AF"),
        IsoCountryInfo("Cook Islands", "184", "CK", "COK", "+682", "NZD", "OC"),
        IsoCountryInfo("Costa Rica", "188", "CR", "CRI", "+506", "CRC", "NA"),
        IsoCountryInfo("Côte d'Ivoire", "384", "CI", "CIV", "+225", "XOF", "AF"),
        IsoCountryInfo("Croatia", "191", "HR", "HRV", "+385", "HRK", "EU"),
        IsoCountryInfo("Cuba", "192", "CU", "CUB", "+53", "CUP", "NA"),
        IsoCountryInfo("Curaçao", "531", "CW", "CUW", "+599", "ANG", ""),
        IsoCountryInfo("Cyprus", "196", "CY", "CYP", "+357", "EUR", "AS"),
        IsoCountryInfo("Czech Republic", "203", "CZ", "CZE", "+420", "CZK", "EU"),
        IsoCountryInfo("Denmark", "208", "DK", "DNK", "+45", "DKK", "EU"),
        IsoCountryInfo("Djibouti", "262", "DJ", "DJI", "+253", "DJF", "AF"),
        IsoCountryInfo("Dominica", "212", "DM", "DMA", "+767", "XCD", "NA"),
        IsoCountryInfo("Dominican Republic", "214", "DO", "DOM", "+809", "DOP", "NA"),
        IsoCountryInfo("Ecuador", "218", "EC", "ECU", "+593", "USD", "SA"),
        IsoCountryInfo("Egypt", "818", "EG", "EGY", "+20", "EGP", "AF"),
        IsoCountryInfo("El Salvador", "222", "SV", "SLV", "+503", "SVC", "NA"),
        IsoCountryInfo("Equatorial Guinea", "226", "GQ", "GNQ", "+240", "XAF", "AF"),
        IsoCountryInfo("Eritrea", "232", "ER", "ERI", "+291", "ETB", "AF"),
        IsoCountryInfo("Estonia", "233", "EE", "EST", "+372", "EUR", "EU"),
        IsoCountryInfo("Ethiopia", "231", "ET", "ETH", "+251", "ETB", "AF"),
        IsoCountryInfo("Falkland Islands (Malvinas)", "238", "FK", "FLK", "+500", "FKP", "SA"),
        IsoCountryInfo("Faroe Islands", "234", "FO", "FRO", "+298", "DKK", "EU"),
        IsoCountryInfo("Fiji", "242", "FJ", "FJI", "+679", "FJD", "OC"),
        IsoCountryInfo("Finland", "246", "FI", "FIN", "+358", "EUR", "EU"),
        IsoCountryInfo("France", "250", "FR", "FRA", "+33", "EUR", "EU"),
        IsoCountryInfo("French Guiana", "254", "GF", "GUF", "+594", "EUR", "SA"),
        IsoCountryInfo("French Polynesia", "258", "PF", "PYF", "+689", "XPF", "OC"),
        IsoCountryInfo("French Southern Territories", "260", "TF", "ATF", "+689", "EUR", "AN"),
        IsoCountryInfo("Gabon", "266", "GA", "GAB", "+241", "XAF", "AF"),
        IsoCountryInfo("Gambia", "270", "GM", "GMB", "+220", "GMD", "AF"),
        IsoCountryInfo("Georgia", "268", "GE", "GEO", "+995", "GEL", "AS"),
        IsoCountryInfo("Germany", "276", "DE", "DEU", "+49", "EUR", "EU"),
        IsoCountryInfo("Ghana", "288", "GH", "GHA", "+233", "GHS", "AF"),
        IsoCountryInfo("Gibraltar", "292", "GI", "GIB", "+350", "GIP", "EU"),
        IsoCountryInfo("Greece", "300", "GR", "GRC", "+30", "EUR", "EU"),
        IsoCountryInfo("Greenland", "304", "GL", "GRL", "+299", "DKK", "NA"),
        IsoCountryInfo("Grenada", "308", "GD", "GRD", "+473", "XCD", "NA"),
        IsoCountryInfo("Guadeloupe", "312", "GP", "GLP", "+590", "EUR", "NA"),
        IsoCountryInfo("Guam", "316", "GU", "GUM", "+671", "USD", "OC"),
        IsoCountryInfo("Guatemala", "320", "GT", "GTM", "+502", "GTQ", "NA"),
        IsoCountryInfo("Guernsey", "831", "GG", "GGY", "+1481", "GGP", "EU"),
        IsoCountryInfo("Guinea", "324", "GN", "GIN", "+225", "GNF", "AF"),
        IsoCountryInfo("Guinea-Bissau", "624", "GW", "GNB", "+245", "XOF", "AF"),
        IsoCountryInfo("Guyana", "328", "GY", "GUY", "+592", "GYD", "SA"),
        IsoCountryInfo("Haiti", "332", "HT", "HTI", "+509", "HTG", "NA"),
        IsoCountryInfo("Heard Island and McDonald Islands", "334", "HM", "HMD", "+61", "AUD", "AN"),
        IsoCountryInfo("Holy See (Vatican City State)", "336", "VA", "VAT", "+379", "EUR", "EU"),
        IsoCountryInfo("Honduras", "340", "HN", "HND", "+504", "HNL", "NA"),
        IsoCountryInfo("Hong Kong", "344", "HK", "HKG", "+852", "HKD", "AS"),
        IsoCountryInfo("Hungary", "348", "HU", "HUN", "+36", "HUF", "EU"),
        IsoCountryInfo("Iceland", "352", "IS", "ISL", "+354", "ISK", "EU"),
        IsoCountryInfo("India", "356", "IN", "IND", "+91", "INR", "AS"),
        IsoCountryInfo("Indonesia", "360", "ID", "IDN", "+62", "IDR", "AS"),
        IsoCountryInfo("Iran, Islamic Republic of", "364", "IR", "IRN", "+98", "IRR", "AS"),
        IsoCountryInfo("Iraq", "368", "IQ", "IRQ", "+964", "IQD", "AS"),
        IsoCountryInfo("Ireland", "372", "IE", "IRL", "+353", "EUR", "EU"),
        IsoCountryInfo("Isle of Man", "833", "IM", "IMN", "+44", "IMP", "EU"),
        IsoCountryInfo("Israel", "376", "IL", "ISR", "+972", "ILS", "AS"),
        IsoCountryInfo("Italy", "380", "IT", "ITA", "+39", "EUR", "EU"),
        IsoCountryInfo("Jamaica", "388", "JM", "JAM", "+876", "JMD", "NA"),
        IsoCountryInfo("Japan", "392", "JP", "JPN", "+81", "JPY", "AS"),
        IsoCountryInfo("Jersey", "832", "JE", "JEY", "+44", "JEP", "EU"),
        IsoCountryInfo("Jordan", "400", "JO", "JOR", "+962", "JOD", "AS"),
        IsoCountryInfo("Kazakhstan", "398", "KZ", "KAZ", "+7", "KZT", "AS"),
        IsoCountryInfo("Kenya", "404", "KE", "KEN", "+254", "KES", "AF"),
        IsoCountryInfo("Kiribati", "296", "KI", "KIR", "+686", "AUD", "OC"),
        IsoCountryInfo("Korea, Democratic People's Republic of", "408", "KP", "PRK", "+850", "KPW", "AS"),
        IsoCountryInfo("Korea, Republic of", "410", "KR", "KOR", "+82", "KRW", "AS"),
        IsoCountryInfo("Kuwait", "414", "KW", "KWT", "+965", "KWD", "AS"),
        IsoCountryInfo("Kyrgyzstan", "417", "KG", "KGZ", "+996", "KGS", "AS"),
        IsoCountryInfo("Lao People's Democratic Republic", "418", "LA", "LAO", "+856", "LAK", "AS"),
        IsoCountryInfo("Latvia", "428", "LV", "LVA", "+371", "EUR", "EU"),
        IsoCountryInfo("Lebanon", "422", "LB", "LBN", "+961", "LBP", "AS"),
        IsoCountryInfo("Lesotho", "426", "LS", "LSO", "+266", "LSL", "AF"),
        IsoCountryInfo("Liberia", "430", "LR", "LBR", "+231", "LRD", "AF"),
        IsoCountryInfo("Libya", "434", "LY", "LBY", "+218", "LYD", "AF"),
        IsoCountryInfo("Liechtenstein", "438", "LI", "LIE", "+423", "CHF", "EU"),
        IsoCountryInfo("Lithuania", "440", "LT", "LTU", "+370", "LTL", "EU"),
        IsoCountryInfo("Luxembourg", "442", "LU", "LUX", "+352", "EUR", "EU"),
        IsoCountryInfo("Macao", "446", "MO", "MAC", "+853", "MOP", "AS"),
        IsoCountryInfo("Macedonia, the former Yugoslav Republic of", "807", "MK", "MKD", "+389", "MKD", "EU"),
        IsoCountryInfo("Madagascar", "450", "MG", "MDG", "+261", "MGA", "AF"),
        IsoCountryInfo("Malawi", "454", "MW", "MWI", "+265", "MWK", "AF"),
        IsoCountryInfo("Malaysia", "458", "MY", "MYS", "+60", "MYR", "AS"),
        IsoCountryInfo("Maldives", "462", "MV", "MDV", "+960", "MVR", "AS"),
        IsoCountryInfo("Mali", "466", "ML", "MLI", "+223", "XOF", "AF"),
        IsoCountryInfo("Malta", "470", "MT", "MLT", "+356", "EUR", "EU"),
        IsoCountryInfo("Marshall Islands", "584", "MH", "MHL", "+692", "USD", "OC"),
        IsoCountryInfo("Martinique", "474", "MQ", "MTQ", "+596", "EUR", "NA"),
        IsoCountryInfo("Mauritania", "478", "MR", "MRT", "+222", "MRO", "AF"),
        IsoCountryInfo("Mauritius", "480", "MU", "MUS", "+230", "MUR", "AF"),
        IsoCountryInfo("Mayotte", "175", "YT", "MYT", "+262", "EUR", "AF"),
        IsoCountryInfo("Mexico", "484", "MX", "MEX", "+52", "MXN", "NA"),
        IsoCountryInfo("Micronesia, Federated States of", "583", "FM", "FSM", "+691", "USD", "OC"),
        IsoCountryInfo("Moldova, Republic of", "498", "MD", "MDA", "+373", "MDL", "EU"),
        IsoCountryInfo("Monaco", "492", "MC", "MCO", "+355", "EUR", "EU"),
        IsoCountryInfo("Mongolia", "496", "MN", "MNG", "+976", "MNT", "AS"),
        IsoCountryInfo("Montenegro", "499", "ME", "MNE", "+382", "EUR", "EU"),
        IsoCountryInfo("Montserrat", "500", "MS", "MSR", "+664", "XCD", "NA"),
        IsoCountryInfo("Morocco", "504", "MA", "MAR", "+212", "MAD", "AF"),
        IsoCountryInfo("Mozambique", "508", "MZ", "MOZ", "+258", "MZN", "AF"),
        IsoCountryInfo("Myanmar", "104", "MM", "MMR", "+95", "MMK", "AS"),
        IsoCountryInfo("Namibia", "516", "NA", "NAM", "+264", "NAD", "AF"),
        IsoCountryInfo("Nauru", "520", "NR", "NRU", "+674", "AUD", "OC"),
        IsoCountryInfo("Nepal", "524", "NP", "NPL", "+977", "NPR", "AS"),
        IsoCountryInfo("Netherlands", "528", "NL", "NLD", "+31", "EUR", "EU"),
        IsoCountryInfo("New Caledonia", "540", "NC", "NCL", "+687", "XPF", "OC"),
        IsoCountryInfo("New Zealand", "554", "NZ", "NZL", "+64", "NZD", "OC"),
        IsoCountryInfo("Nicaragua", "558", "NI", "NIC", "+505", "NIO", "NA"),
        IsoCountryInfo("Niger", "562", "NE", "NER", "+277", "XOF", "AF"),
        IsoCountryInfo("Nigeria", "566", "NG", "NGA", "+234", "NGN", "AF"),
        IsoCountryInfo("Niue", "570", "NU", "NIU", "+683", "NZD", "OC"),
        IsoCountryInfo("Norfolk Island", "574", "NF", "NFK", "+672", "AUD", "OC"),
        IsoCountryInfo("Northern Mariana Islands", "580", "MP", "MNP", "+670", "USD", "OC"),
        IsoCountryInfo("Norway", "578", "NO", "NOR", "+47", "NOK", "EU"),
        IsoCountryInfo("Oman", "512", "OM", "OMN", "+968", "OMR", "AS"),
        IsoCountryInfo("Pakistan", "586", "PK", "PAK", "+92", "PKR", "AS"),
        IsoCountryInfo("Palau", "585", "PW", "PLW", "+680", "USD", "OC"),
        IsoCountryInfo("Palestine, State of", "275", "PS", "PSE", "+970", "JOD", "AS"),
        IsoCountryInfo("Panama", "591", "PA", "PAN", "+507", "PAB", "NA"),
        IsoCountryInfo("Papua New Guinea", "598", "PG", "PNG", "+675", "PGK", "OC"),
        IsoCountryInfo("Paraguay", "600", "PY", "PRY", "+595", "PYG", "SA"),
        IsoCountryInfo("Peru", "604", "PE", "PER", "+51", "PEN", "SA"),
        IsoCountryInfo("Philippines", "608", "PH", "PHL", "+63", "PHP", "AS"),
        IsoCountryInfo("Pitcairn", "612", "PN", "PCN", "+872", "NZD", "OC"),
        IsoCountryInfo("Poland", "616", "PL", "POL", "+48", "PLN", "EU"),
        IsoCountryInfo("Portugal", "620", "PT", "PRT", "+351", "EUR", "EU"),
        IsoCountryInfo("Puerto Rico", "630", "PR", "PRI", "+787", "USD", "NA"),
        IsoCountryInfo("Qatar", "634", "QA", "QAT", "+974", "QAR", "AS"),
        IsoCountryInfo("Réunion", "638", "RE", "REU", "+262", "EUR", "AF"),
        IsoCountryInfo("Romania", "642", "RO", "ROU", "+40", "RON", "EU"),
        IsoCountryInfo("Russian Federation", "643", "RU", "RUS", "+7", "RUB", "EU"),
        IsoCountryInfo("Rwanda", "646", "RW", "RWA", "+250", "RWF", "AF"),
        IsoCountryInfo("Saint Barthélemy", "652", "BL", "BLM", "+590", "EUR", "NA"),
        IsoCountryInfo("Saint Helena, Ascension and Tristan da Cunha", "654", "SH", "SHN", "+290", "SHP", "AF"),
        IsoCountryInfo("Saint Kitts and Nevis", "659", "KN", "KNA", "+869", "XCD", "NA"),
        IsoCountryInfo("Saint Lucia", "662", "LC", "LCA", "+758", "XCD", "NA"),
        IsoCountryInfo("Saint Martin (French part)", "663", "MF", "MAF", "+590", "EUR", "NA"),
        IsoCountryInfo("Saint Pierre and Miquelon", "666", "PM", "SPM", "+508", "EUR", "NA"),
        IsoCountryInfo("Saint Vincent and the Grenadines", "670", "VC", "VCT", "+784", "XCD", "NA"),
        IsoCountryInfo("Samoa", "882", "WS", "WSM", "+685", "WST", "OC"),
        IsoCountryInfo("San Marino", "674", "SM", "SMR", "+378", "EUR", "EU"),
        IsoCountryInfo("Sao Tome and Principe", "678", "ST", "STP", "+239", "STD", "AF"),
        IsoCountryInfo("Saudi Arabia", "682", "SA", "SAU", "+966", "SAR", "AS"),
        IsoCountryInfo("Senegal", "686", "SN", "SEN", "+221", "XOF", "AF"),
        IsoCountryInfo("Serbia", "688", "RS", "SRB", "+381", "RSD", "EU"),
        IsoCountryInfo("Seychelles", "690", "SC", "SYC", "+248", "SCR", "AF"),
        IsoCountryInfo("Sierra Leone", "694", "SL", "SLE", "+232", "SLL", "AF"),
        IsoCountryInfo("Singapore", "702", "SG", "SGP", "+65", "SGD", "AS"),
        IsoCountryInfo("Sint Maarten (Dutch part)", "534", "SX", "SXM", "+599", "ANG", ""),
        IsoCountryInfo("Slovakia", "703", "SK", "SVK", "+421", "SKK", "EU"),
        IsoCountryInfo("Slovenia", "705", "SI", "SVN", "+386", "EUR", "EU"),
        IsoCountryInfo("Solomon Islands", "090", "SB", "SLB", "+677", "SBD", "OC"),
        IsoCountryInfo("Somalia", "706", "SO", "SOM", "+252", "SOS", "AF"),
        IsoCountryInfo("South Africa", "710", "ZA", "ZAF", "+27", "ZAR", "AF"),
        IsoCountryInfo("South Georgia and the South Sandwich Islands", "239", "GS", "SGS", "+500", "GBP", "AN"),
        IsoCountryInfo("South Sudan", "728", "SS", "SSD", "+211", "SSP", ""),
        IsoCountryInfo("Spain", "724", "ES", "ESP", "+34", "EUR", "EU"),
        IsoCountryInfo("Sri Lanka", "144", "LK", "LKA", "+94", "LKR", "AS"),
        IsoCountryInfo("Sudan", "729", "SD", "SDN", "+249", "SDG", "AF"),
        IsoCountryInfo("Suriname", "740", "SR", "SUR", "+597", "SRD", "SA"),
        IsoCountryInfo("Svalbard and Jan Mayen", "744", "SJ", "SJM", "+47", "NOK", "EU"),
        IsoCountryInfo("Swaziland", "748", "SZ", "SWZ", "+268", "CHF", "AF"),
        IsoCountryInfo("Sweden", "752", "SE", "SWE", "+46", "SEK", "EU"),
        IsoCountryInfo("Switzerland", "756", "CH", "CHE", "+41", "CHF", "EU"),
        IsoCountryInfo("Syrian Arab Republic", "760", "SY", "SYR", "+963", "SYP", "AS"),
        IsoCountryInfo("Taiwan, Province of China", "158", "TW", "TWN", "+886", "TWD", "AS"),
        IsoCountryInfo("Tajikistan", "762", "TJ", "TJK", "+992", "TJS", "AS"),
        IsoCountryInfo("Tanzania, United Republic of", "834", "TZ", "TZA", "+255", "TZS", "AF"),
        IsoCountryInfo("Thailand", "764", "TH", "THA", "+66", "THB", "AS"),
        IsoCountryInfo("Timor-Leste", "626", "TL", "TLS", "+670", "IDR", "AS"),
        IsoCountryInfo("Togo", "768", "TG", "TGO", "+228", "XOF", "AF"),
        IsoCountryInfo("Tokelau", "772", "TK", "TKL", "+690", "NZD", "OC"),
        IsoCountryInfo("Tonga", "776", "TO", "TON", "+676", "TOP", "OC"),
        IsoCountryInfo("Trinidad and Tobago", "780", "TT", "TTO", "+868", "TTD", "NA"),
        IsoCountryInfo("Tunisia", "788", "TN", "TUN", "+216", "TND", "AF"),
        IsoCountryInfo("Turkey", "792", "TR", "TUR", "+90", "TRY", "EU"),
        IsoCountryInfo("Turkmenistan", "795", "TM", "TKM", "+993", "TMM", "AS"),
        IsoCountryInfo("Turks and Caicos Islands", "796", "TC", "TCA", "+649", "USD", "NA"),
        IsoCountryInfo("Tuvalu", "798", "TV", "TUV", "+688", "TVD", "OC"),
        IsoCountryInfo("Uganda", "800", "UG", "UGA", "+256", "UGX", "AF"),
        IsoCountryInfo("Ukraine", "804", "UA", "UKR", "+380", "UAH", "EU"),
        IsoCountryInfo("United Arab Emirates", "784", "AE", "ARE", "+971", "AED", "AS"),
        IsoCountryInfo("United Kingdom", "826", "GB", "GBR", "+44", "GBP", "EU"),
        IsoCountryInfo("United States", "840", "US", "USA", "+1", "USD", "NA"),
        IsoCountryInfo("United States Minor Outlying Islands", "581", "UM", "UMI", "+1", "USD", "OC"),
        IsoCountryInfo("Uruguay", "858", "UY", "URY", "+598", "UYU", "SA"),
        IsoCountryInfo("Uzbekistan", "860", "UZ", "UZB", "+998", "UZS", "AS"),
        IsoCountryInfo("Vanuatu", "548", "VU", "VUT", "+678", "VUV", "OC"),
        IsoCountryInfo("Venezuela, Bolivarian Republic of", "862", "VE", "VEN", "+58", "VEF", "SA"),
        IsoCountryInfo("Vietnam", "704", "VN", "VNM", "+84", "VND", "AS"),
        IsoCountryInfo("Virgin Islands, British", "092", "VG", "VGB", "+284", "USD", "NA"),
        IsoCountryInfo("Virgin Islands, U.S.", "850", "VI", "VIR", "+340", "USD", "NA"),
        IsoCountryInfo("Wallis and Futuna", "876", "WF", "WLF", "+681", "XPF", "OC"),
        IsoCountryInfo("Western Sahara", "732", "EH", "ESH", "+212", "MAD", "AF"),
        IsoCountryInfo("Yemen", "887", "YE", "YEM", "+967", "YER", "AS"),
        IsoCountryInfo("Zambia", "894", "ZM", "ZMB", "+260", "ZMW", "AF"),
        IsoCountryInfo("Zimbabwe", "716", "ZW", "ZWE", "+263", "ZWD", "AF")
    )

    fun euCountries(): List<IsoCountryInfo> {
        return allCountries.filter { it.continent == "EU" }
    }

    fun countryForCode(code: String?): IsoCountryInfo? {
        return allCountries.find { it.alpha2 == code }
    }
}